include:
   - infrastructure.yaml
services:
    do-it-api:
        build:
            context: .
        ports: 
            - "5000:5000"
        restart: unless-stopped
        depends_on:
            do-it-database:
                condition: service_healthy
        environment:
            - Database__ConnectionStrings__DoItDb=Host=do-it-database;Port=5432;Database=do-it;Username=root;Password=123456;     