services:
    do-it-database:
        image: postgres
        restart: unless-stopped
        environment:
            - "POSTGRES_USER=root"
            - "POSTGRES_PASSWORD=123456"
            - "POSTGRES_DB=do-it"
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "psql -U root -d do-it -c 'SELECT 1' || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 5
     
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"

volumes:
    db-data:     